@include('partials.errors')
<div class="row g-3">
    <div class="col-md-3"><label class="form-label">Date</label><input class="form-control" type="date" name="date" value="{{ old('date', isset($sale) ? $sale->date->format('Y-m-d') : now()->format('Y-m-d')) }}" required></div>
    <div class="col-md-3"><label class="form-label">Date / Time</label><input class="form-control" type="datetime-local" name="sold_at" value="{{ old('sold_at', isset($sale) ? $sale->sold_at->format('Y-m-d\\TH:i') : now()->format('Y-m-d\\TH:i')) }}" required></div>
    <div class="col-md-6"><label class="form-label">Item</label><select class="form-select sale-item" name="item_id" required><option value="">Select item</option>@foreach($items as $item)@php($availableStock = $item->current_stock + ((isset($sale) && $sale->item_id === $item->id) ? $sale->quantity : 0))<option value="{{ $item->id }}" data-price="{{ $item->default_selling_price }}" data-stock="{{ $availableStock }}" @selected(old('item_id', $sale->item_id ?? $selectedItemId ?? '') == $item->id)>{{ $item->name }} (Available: {{ $availableStock }})</option>@endforeach</select><small class="text-muted sale-stock-help">Select an item to see available stock.</small></div>
    <div class="col-md-3"><label class="form-label">Quantity</label><input class="form-control sale-qty" type="number" min="1" name="quantity" value="{{ old('quantity', $sale->quantity ?? 1) }}" required><small class="text-danger sale-stock-warning d-none">Quantity is more than available stock.</small></div>
    <div class="col-md-3"><label class="form-label">Price Per Item</label><input class="form-control sale-price" type="number" step="0.01" min="0" name="price_per_item" value="{{ old('price_per_item', $sale->price_per_item ?? $selectedItem?->default_selling_price ?? 0) }}" required></div>
    <div class="col-md-3"><label class="form-label">Total Sales</label><input class="form-control sale-total" type="number" step="0.01" min="0" name="total_sales_price" value="{{ old('total_sales_price', $sale->total_sales_price ?? '') }}"></div>
    <div class="col-md-3"><label class="form-label">Payment</label><select class="form-select" name="payment_mode">@foreach($paymentModes as $mode)<option value="{{ $mode }}" @selected(old('payment_mode', $sale->payment_mode ?? 'Cash') === $mode)>{{ $mode }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Customer Name</label><input class="form-control" name="customer_name" value="{{ old('customer_name', $sale->customer_name ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">Customer Phone</label><input class="form-control" name="customer_phone" value="{{ old('customer_phone', $sale->customer_phone ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">Customer Address</label><input class="form-control" name="customer_address" value="{{ old('customer_address', $sale->customer_address ?? '') }}"></div>
    <div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" name="notes" rows="3">{{ old('notes', $sale->notes ?? '') }}</textarea></div>
</div>
<div class="mt-3"><button class="btn btn-primary">Save</button><a class="btn btn-light" href="{{ route('sales.index') }}">Cancel</a></div>
@push('scripts')<script>const item=document.querySelector('.sale-item'),qty=document.querySelector('.sale-qty'),price=document.querySelector('.sale-price'),total=document.querySelector('.sale-total'),stockHelp=document.querySelector('.sale-stock-help'),stockWarning=document.querySelector('.sale-stock-warning');function selectedStock(){return parseInt(item?.selectedOptions[0]?.dataset.stock||0,10)}function syncStockUi(){const stock=selectedStock();if(stockHelp){stockHelp.textContent=item?.value?`Available stock: ${stock}`:'Select an item to see available stock.'}if(qty){qty.max=item?.value?stock:''}stockWarning?.classList.toggle('d-none',!(item?.value&&parseInt(qty?.value||0,10)>stock))}function calcSale(){if(!total.value){total.value=((parseFloat(qty.value||0))*parseFloat(price.value||0)).toFixed(2)}syncStockUi()}item?.addEventListener('change',()=>{price.value=item.selectedOptions[0]?.dataset.price||0;total.value='';calcSale()});[qty,price].forEach(el=>el?.addEventListener('input',()=>{total.value='';calcSale()}));calcSale();</script>@endpush
